### ISSUE TITLE
Question about the date (ds) 

### ISSUE THREAD

**Issue by stuckel** [favstats/metatargetr#1]
Hey Fabio, 

this is a great package! Could you perhaps specify if the date (ds) that is indicated as the endpoint of the 7 or 30 day period is inclusive that day or exclusive. I ask because if I run the get_targeting() command today I get as date the "2023-02-13", however if I check the Meta Ad Library today I get for 7 days : 06.02.2023-12.02.2023. 
best, Simon

**Comment by favstats** [comment]
Hi Simon,

as far as I can tell (as you can imagine there is no official documentation for this), the ds date is *exclusive* of the time period as it always seems to one day later of what is available in the UI (and ultimately the UI is where I am retrieving this data from).

Hope that helps!

**Comment by stuckel** [comment]
Thanks for the clarification !
